/**
 * Word Bank for Imposter Game
 */

const wordBank = {
  sports: ['Basketball', 'Soccer', 'Tennis', 'Baseball', 'Football', 'Volleyball', 'Swimming', 'Golf', 'Boxing', 'Hockey', 'Rugby', 'Cricket', 'Badminton', 'Table Tennis', 'Skiing', 'Snowboarding', 'Surfing', 'Skateboarding', 'Wrestling', 'Martial Arts', 'Karate', 'Judo', 'Taekwondo', 'Fencing', 'Archery', 'Gymnastics', 'Track and Field', 'Marathon', 'Cycling', 'Mountain Biking', 'Rowing', 'Kayaking', 'Canoeing', 'Sailing', 'Diving', 'Water Polo', 'Polo', 'Lacrosse', 'Field Hockey', 'Handball', 'Squash', 'Racquetball', 'Bowling', 'Billiards', 'Darts', 'Rock Climbing', 'Ice Skating', 'Figure Skating', 'Speed Skating', 'Curling', 'Bobsledding', 'Luge', 'Biathlon', 'Triathlon', 'Decathlon', 'Pentathlon', 'Shot Put', 'Discus', 'Javelin', 'Hammer Throw', 'Pole Vault', 'High Jump', 'Long Jump', 'Triple Jump', 'Hurdles', 'Steeplechase', 'Sprint', 'Relay', 'CrossFit', 'Weightlifting', 'Powerlifting', 'Bodybuilding', 'Yoga', 'Pilates', 'Aerobics', 'Zumba', 'Dance', 'Cheerleading', 'Synchronized Swimming', 'Rhythmic Gymnastics', 'BMX', 'Motocross', 'Formula 1', 'NASCAR', 'Rally', 'Drag Racing', 'MMA', 'Kickboxing', 'Muay Thai', 'Jiu Jitsu', 'Sumo', 'Rodeo', 'Bull Riding', 'Equestrian', 'Show Jumping', 'Dressage', 'Horse Racing', 'Dog Racing', 'Paintball', 'Airsoft'],
  animals: ['Dog', 'Cat', 'Elephant', 'Lion', 'Tiger', 'Giraffe', 'Zebra', 'Monkey', 'Bear', 'Penguin', 'Dolphin', 'Whale', 'Shark', 'Octopus', 'Jellyfish', 'Seahorse', 'Starfish', 'Crab', 'Lobster', 'Shrimp', 'Eagle', 'Hawk', 'Owl', 'Parrot', 'Peacock', 'Flamingo', 'Swan', 'Duck', 'Goose', 'Chicken', 'Rooster', 'Turkey', 'Ostrich', 'Emu', 'Kangaroo', 'Koala', 'Panda', 'Polar Bear', 'Grizzly Bear', 'Black Bear', 'Gorilla', 'Chimpanzee', 'Orangutan', 'Baboon', 'Lemur', 'Sloth', 'Anteater', 'Armadillo', 'Hedgehog', 'Porcupine', 'Squirrel', 'Chipmunk', 'Rabbit', 'Hare', 'Beaver', 'Otter', 'Seal', 'Walrus', 'Manatee', 'Hippopotamus', 'Rhinoceros', 'Crocodile', 'Alligator', 'Turtle', 'Tortoise', 'Lizard', 'Iguana', 'Chameleon', 'Gecko', 'Snake', 'Python', 'Cobra', 'Rattlesnake', 'Frog', 'Toad', 'Salamander', 'Wolf', 'Fox', 'Coyote', 'Jackal', 'Hyena', 'Cheetah', 'Leopard', 'Jaguar', 'Panther', 'Lynx', 'Cougar', 'Deer', 'Elk', 'Moose', 'Reindeer', 'Antelope', 'Gazelle', 'Buffalo', 'Bison', 'Ox', 'Yak', 'Camel', 'Llama', 'Alpaca'],
  countries: ['USA', 'Canada', 'Mexico', 'Brazil', 'Argentina', 'Chile', 'Colombia', 'Peru', 'Venezuela', 'Ecuador', 'Bolivia', 'Paraguay', 'Uruguay', 'France', 'Germany', 'Italy', 'Spain', 'Portugal', 'United Kingdom', 'Ireland', 'Netherlands', 'Belgium', 'Switzerland', 'Austria', 'Poland', 'Czech Republic', 'Hungary', 'Romania', 'Greece', 'Turkey', 'Russia', 'Ukraine', 'Sweden', 'Norway', 'Denmark', 'Finland', 'Iceland', 'Japan', 'China', 'South Korea', 'North Korea', 'Thailand', 'Vietnam', 'Indonesia', 'Malaysia', 'Singapore', 'Philippines', 'India', 'Pakistan', 'Bangladesh', 'Nepal', 'Sri Lanka', 'Myanmar', 'Cambodia', 'Laos', 'Mongolia', 'Kazakhstan', 'Uzbekistan', 'Afghanistan', 'Iran', 'Iraq', 'Saudi Arabia', 'United Arab Emirates', 'Israel', 'Jordan', 'Lebanon', 'Syria', 'Egypt', 'Libya', 'Tunisia', 'Algeria', 'Morocco', 'Sudan', 'Ethiopia', 'Kenya', 'Tanzania', 'Uganda', 'Somalia', 'South Africa', 'Nigeria', 'Ghana', 'Senegal', 'Mali', 'Zimbabwe', 'Botswana', 'Namibia', 'Zambia', 'Mozambique', 'Madagascar', 'Australia', 'New Zealand', 'Papua New Guinea', 'Fiji', 'Cuba', 'Jamaica', 'Haiti', 'Dominican Republic', 'Puerto Rico', 'Costa Rica', 'Panama', 'Guatemala', 'Honduras', 'Nicaragua', 'El Salvador'],
  places: ['City', 'Park', 'Harbor', 'Port', 'Marina', 'Pier', 'Dock', 'Lighthouse', 'Bridge', 'Tunnel', 'Highway', 'Road', 'Street', 'Avenue', 'Boulevard', 'Alley', 'Square', 'Plaza', 'Mall', 'Market', 'Bazaar', 'Store', 'Shop', 'Restaurant', 'Cafe', 'Bar', 'Pub', 'Club', 'Theater', 'Cinema', 'Museum', 'Gallery', 'Library', 'Bookstore', 'School', 'University', 'College', 'Hospital', 'Clinic', 'Pharmacy', 'Bank', 'Post Office', 'Police Station', 'Fire Station', 'Airport', 'Train Station', 'Bus Station', 'Subway', 'Hotel', 'Motel', 'Resort', 'Spa', 'Gym', 'Stadium', 'Arena', 'Field', 'Court', 'Track', 'Pool', 'Aquarium', 'Zoo', 'Garden', 'Greenhouse', 'Farm', 'Ranch', 'Barn', 'Stable', 'Vineyard', 'Orchard', 'Plantation', 'Factory', 'Warehouse', 'Workshop', 'Studio', 'Laboratory', 'Observatory', 'Planetarium', 'Convention Center', 'Auditorium', 'Amphitheater', 'Coliseum', 'Courthouse', 'Capitol', 'Embassy', 'Consulate', 'Temple', 'Church', 'Mosque', 'Synagogue', 'Cathedral', 'Monastery', 'Abbey', 'Shrine', 'Memorial', 'Monument', 'Statue', 'Fountain', 'Pavilion', 'Gazebo', 'Bandstand', 'Kiosk'],
  books: ['Harry Potter', 'Lord of the Rings', 'Percy Jackson', 'The Hobbit', 'Narnia', 'Twilight', 'Hunger Games', 'Divergent', 'Maze Runner', '1984', 'Animal Farm', 'Brave New World', 'Fahrenheit 451', 'To Kill a Mockingbird', 'The Great Gatsby', 'Pride and Prejudice', 'Jane Eyre', 'Wuthering Heights', 'Moby Dick', 'War and Peace', 'Crime and Punishment', 'The Brothers Karamazov', 'The Catcher in the Rye', 'Of Mice and Men', 'The Grapes of Wrath', 'East of Eden', 'The Old Man and the Sea', 'For Whom the Bell Tolls', 'A Farewell to Arms', 'The Sun Also Rises', 'The Scarlet Letter', 'The Adventures of Huckleberry Finn', 'Tom Sawyer', 'Treasure Island', 'Robinson Crusoe', 'Gulliver\'s Travels', 'Don Quixote', 'Les Miserables', 'The Count of Monte Cristo', 'The Three Musketeers', 'Dracula', 'Frankenstein', 'Dr. Jekyll and Mr. Hyde', 'The Picture of Dorian Gray', 'Sherlock Holmes', 'Agatha Christie', 'Gone with the Wind', 'The Shining', 'It', 'The Stand', 'Carrie', 'Pet Sematary', 'Game of Thrones', 'Dune', 'Foundation', 'Ender\'s Game', 'The Martian', 'Ready Player One', 'The Hitchhiker\'s Guide', 'Catch-22', 'Slaughterhouse-Five', 'The Handmaid\'s Tale', 'Margaret Atwood', 'The Road', 'Blood Meridian', 'All the Pretty Horses', 'Beloved', 'The Color Purple', 'Their Eyes Were Watching God', 'Invisible Man', 'Native Son', 'The Bluest Eye', 'The Giver', 'Number the Stars', 'Bridge to Terabithia', 'Charlotte\'s Web', 'Where the Wild Things Are', 'Goodnight Moon', 'The Very Hungry Caterpillar', 'Green Eggs and Ham', 'Cat in the Hat', 'Matilda', 'Charlie and the Chocolate Factory', 'James and the Giant Peach', 'The BFG', 'Fantastic Mr. Fox', 'The Witches', 'Alice in Wonderland', 'Peter Pan', 'The Wizard of Oz', 'The Secret Garden', 'Little Women', 'Anne of Green Gables', 'A Little Princess', 'Black Beauty', 'Call of the Wild', 'White Fang'],
  school: ['Teacher', 'Student', 'Classroom', 'Homework', 'Test', 'Library', 'Cafeteria', 'Principal', 'Textbook', 'Locker', 'Desk', 'Chair', 'Blackboard', 'Whiteboard', 'Chalkboard', 'Eraser', 'Marker', 'Chalk', 'Pencil', 'Pen', 'Notebook', 'Binder', 'Folder', 'Paper', 'Ruler', 'Calculator', 'Computer', 'Tablet', 'Laptop', 'Projector', 'Screen', 'Map', 'Globe', 'Dictionary', 'Encyclopedia', 'Atlas', 'Backpack', 'Lunchbox', 'Water Bottle', 'Gym', 'Playground', 'Field', 'Track', 'Basketball Court', 'Soccer Field', 'Baseball Diamond', 'Tennis Court', 'Pool', 'Auditorium', 'Stage', 'Hallway', 'Corridor', 'Staircase', 'Elevator', 'Bathroom', 'Restroom', 'Office', 'Nurse', 'Counselor', 'Secretary', 'Janitor', 'Bus', 'Driver', 'Schedule', 'Timetable', 'Period', 'Recess', 'Lunch', 'Break', 'Bell', 'Announcement', 'Assembly', 'Pep Rally', 'Homecoming', 'Prom', 'Dance', 'Club', 'Sports Team', 'Band', 'Orchestra', 'Choir', 'Drama', 'Art Class', 'Science Lab', 'Chemistry', 'Biology', 'Physics', 'Math', 'Algebra', 'Geometry', 'Calculus', 'English', 'Literature', 'History', 'Geography', 'Social Studies', 'Foreign Language', 'Spanish', 'French'],
  professions: ['Doctor', 'Lawyer', 'Engineer', 'Teacher', 'Chef', 'Pilot', 'Artist', 'Musician', 'Athlete', 'Scientist', 'Nurse', 'Dentist', 'Pharmacist', 'Veterinarian', 'Architect', 'Accountant', 'Banker', 'Economist', 'Programmer', 'Developer', 'Designer', 'Photographer', 'Videographer', 'Journalist', 'Reporter', 'Editor', 'Writer', 'Author', 'Poet', 'Librarian', 'Professor', 'Researcher', 'Biologist', 'Chemist', 'Physicist', 'Astronomer', 'Geologist', 'Meteorologist', 'Archaeologist', 'Anthropologist', 'Psychologist', 'Psychiatrist', 'Therapist', 'Counselor', 'Social Worker', 'Police Officer', 'Detective', 'Firefighter', 'Paramedic', 'EMT', 'Soldier', 'Sailor', 'Marine', 'Air Force', 'Coast Guard', 'Judge', 'Prosecutor', 'Public Defender', 'Paralegal', 'Real Estate Agent', 'Broker', 'Insurance Agent', 'Sales Representative', 'Retail Worker', 'Cashier', 'Waiter', 'Waitress', 'Bartender', 'Barista', 'Baker', 'Butcher', 'Farmer', 'Rancher', 'Fisher', 'Carpenter', 'Plumber', 'Electrician', 'Mechanic', 'Welder', 'Mason', 'Painter', 'Roofer', 'Landscaper', 'Gardener', 'Janitor', 'Housekeeper', 'Maid', 'Nanny', 'Babysitter', 'Tutor', 'Coach', 'Trainer', 'Referee', 'Umpire', 'Actor', 'Actress', 'Director', 'Producer', 'Screenwriter'],
  movies: ['Avatar', 'Titanic', 'Star Wars', 'Avengers', 'Jurassic Park', 'The Matrix', 'Frozen', 'Inception', 'Interstellar', 'Gladiator', 'The Dark Knight', 'Forrest Gump', 'Pulp Fiction', 'The Shawshank Redemption', 'The Godfather', 'Fight Club', 'Goodfellas', 'The Silence of the Lambs', 'Schindler\'s List', 'Saving Private Ryan', 'The Green Mile', 'Cast Away', 'Catch Me If You Can', 'The Terminal', 'Bridge of Spies', 'Lincoln', 'Django Unchained', 'Inglourious Basterds', 'Kill Bill', 'Reservoir Dogs', 'The Hateful Eight', 'Once Upon a Time in Hollywood', 'Parasite', 'Joker', 'Black Panther', 'Spider-Man', 'Iron Man', 'Captain America', 'Thor', 'Guardians of the Galaxy', 'Ant-Man', 'Doctor Strange', 'Black Widow', 'Shang-Chi', 'Eternals', 'Batman', 'Superman', 'Wonder Woman', 'Aquaman', 'Shazam', 'The Suicide Squad', 'Justice League', 'Man of Steel', 'Batman Begins', 'The Lion King', 'Aladdin', 'Beauty and the Beast', 'The Little Mermaid', 'Mulan', 'Pocahontas', 'Hercules', 'Tarzan', 'Finding Nemo', 'Finding Dory', 'Monsters Inc', 'Toy Story', 'The Incredibles', 'Up', 'WALL-E', 'Ratatouille', 'Cars', 'Brave', 'Inside Out', 'Coco', 'Soul', 'Luca', 'Turning Red', 'Encanto', 'Moana', 'Tangled', 'Wreck-It Ralph', 'Zootopia', 'Big Hero 6', 'The Hunger Games', 'Twilight', 'Harry Potter', 'Lord of the Rings', 'The Hobbit', 'Pirates of the Caribbean', 'Fast and Furious', 'Mission Impossible', 'James Bond', 'Indiana Jones', 'Back to the Future', 'Terminator', 'Alien'],
  food: ['Pizza', 'Burger', 'Sushi', 'Pasta', 'Tacos', 'Salad', 'Steak', 'Ice Cream', 'Cake', 'Sandwich', 'Burrito', 'Quesadilla', 'Nachos', 'Fajitas', 'Enchiladas', 'Tamales', 'Chili', 'Soup', 'Stew', 'Curry', 'Rice', 'Noodles', 'Ramen', 'Pho', 'Pad Thai', 'Fried Rice', 'Biryani', 'Paella', 'Risotto', 'Lasagna', 'Spaghetti', 'Fettuccine', 'Penne', 'Ravioli', 'Gnocchi', 'Carbonara', 'Alfredo', 'Marinara', 'Bolognese', 'Pesto', 'Pizza Margherita', 'Pepperoni Pizza', 'Hawaiian Pizza', 'BBQ Chicken Pizza', 'Cheeseburger', 'Bacon Burger', 'Veggie Burger', 'Fish Burger', 'Chicken Burger', 'Hot Dog', 'Corn Dog', 'Bratwurst', 'Sausage', 'Bacon', 'Ham', 'Salami', 'Pepperoni', 'Prosciutto', 'Pastrami', 'Roast Beef', 'Turkey', 'Chicken', 'Duck', 'Pork', 'Lamb', 'Veal', 'Salmon', 'Tuna', 'Shrimp', 'Lobster', 'Crab', 'Oysters', 'Clams', 'Mussels', 'Scallops', 'Calamari', 'Octopus', 'Sashimi', 'Nigiri', 'Roll', 'Tempura', 'Teriyaki', 'Yakitori', 'Gyoza', 'Dumpling', 'Wonton', 'Spring Roll', 'Egg Roll', 'Fried Chicken', 'Grilled Chicken', 'Roasted Chicken', 'BBQ Ribs', 'Pulled Pork', 'Brisket', 'Meatloaf', 'Meatballs', 'Kebab', 'Shawarma', 'Falafel', 'Hummus'],
  candy: ['Chocolate', 'Snickers', 'M&Ms', 'Skittles', 'Starburst', 'Twix', 'KitKat', 'Reeses', 'Butterfinger', 'Milky Way', 'Three Musketeers', 'Almond Joy', 'Mounds', 'Hersheys', 'Crunch', 'Krackel', 'Baby Ruth', 'Payday', 'Oh Henry', '100 Grand', 'Whatchamacallit', 'Take 5', 'FastBreak', 'Rolo', 'Caramello', 'Milk Duds', 'Junior Mints', 'York Peppermint Patty', 'Andes Mints', 'After Eight', 'Tootsie Roll', 'Tootsie Pop', 'Blow Pop', 'Dum Dums', 'Jolly Rancher', 'Lifesavers', 'Werther\'s', 'Butterscotch', 'Lollipop', 'Gummy Bears', 'Gummy Worms', 'Sour Patch Kids', 'Swedish Fish', 'Haribo', 'Trolli', 'Black Forest', 'Airheads', 'Laffy Taffy', 'Now and Later', 'Nerds', 'SweeTarts', 'Runts', 'Spree', 'Smarties', 'Rockets', 'Pixie Stix', 'Fun Dip', 'Pixy Stix', 'Pop Rocks', 'Ring Pop', 'Push Pop', 'Warheads', 'Toxic Waste', 'Sour Skittles', 'Sour Starburst', 'Twizzlers', 'Red Vines', 'Licorice', 'Good & Plenty', 'Hot Tamales', 'Mike and Ike', 'Dots', 'Jujubes', 'Jelly Beans', 'Jelly Belly', 'Conversation Hearts', 'Candy Corn', 'Peeps', 'Marshmallows', 'Divinity', 'Fudge', 'Taffy', 'Salt Water Taffy', 'Peanut Brittle', 'Toffee', 'Heath Bar', 'Skor', 'Toblerone', 'Lindt', 'Godiva', 'Ghirardelli', 'Ferrero Rocher', 'Raffaello', 'Kinder', 'Nutella', 'Mars Bar', 'Bounty', 'Aero', 'Smarties UK', 'Cadbury', 'Flake'],
  fictional_creatures: ['Dragon', 'Unicorn', 'Phoenix', 'Griffin', 'Pegasus', 'Centaur', 'Minotaur', 'Hydra', 'Cerberus', 'Basilisk', 'Chimera', 'Sphinx', 'Cyclops', 'Medusa', 'Kraken', 'Leviathan', 'Behemoth', 'Bigfoot', 'Sasquatch', 'Yeti', 'Abominable Snowman', 'Loch Ness Monster', 'Chupacabra', 'Mothman', 'Jersey Devil', 'Wendigo', 'Skinwalker', 'Vampire', 'Werewolf', 'Zombie', 'Ghost', 'Phantom', 'Specter', 'Wraith', 'Banshee', 'Poltergeist', 'Demon', 'Devil', 'Angel', 'Fairy', 'Pixie', 'Sprite', 'Elf', 'Dwarf', 'Gnome', 'Goblin', 'Orc', 'Troll', 'Ogre', 'Giant', 'Titan', 'Golem', 'Mummy', 'Frankenstein', 'Godzilla', 'King Kong', 'Mothra', 'Gorgon', 'Harpy', 'Siren', 'Mermaid', 'Merman', 'Selkie', 'Kelpie', 'Nymph', 'Dryad', 'Naiad', 'Satyr', 'Faun', 'Leprechaun', 'Changeling', 'Brownie', 'Imp', 'Incubus', 'Succubus', 'Djinn', 'Genie', 'Ifrit', 'Thunderbird', 'Roc', 'Garuda', 'Simurgh', 'Hippocampus', 'Hippogriff', 'Wyvern', 'Wyrm', 'Sea Serpent', 'Naga', 'Lamia', 'Manticore', 'Cockatrice', 'Roc', 'Fenrir', 'Sleipnir', 'Jormungandr', 'Valkyrie', 'Frost Giant', 'Fire Giant', 'Balrog', 'Ent', 'Treant'],
  famous_athletes: ['Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Tom Brady', 'Patrick Mahomes', 'Aaron Rodgers', 'Peyton Manning', 'Joe Montana', 'Jerry Rice', 'Randy Moss', 'Cristiano Ronaldo', 'Lionel Messi', 'Neymar', 'Pele', 'Diego Maradona', 'Zinedine Zidane', 'Ronaldinho', 'Mbappe', 'Haaland', 'Wayne Gretzky', 'Sidney Crosby', 'Alex Ovechkin', 'Connor McDavid', 'Mario Lemieux', 'Bobby Orr', 'Serena Williams', 'Venus Williams', 'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Pete Sampras', 'Andre Agassi', 'Maria Sharapova', 'Naomi Osaka', 'Tiger Woods', 'Phil Mickelson', 'Rory McIlroy', 'Jack Nicklaus', 'Arnold Palmer', 'Muhammad Ali', 'Mike Tyson', 'Floyd Mayweather', 'Manny Pacquiao', 'Canelo Alvarez', 'Conor McGregor', 'Khabib Nurmagomedov', 'Jon Jones', 'Anderson Silva', 'Georges St-Pierre', 'Usain Bolt', 'Michael Phelps', 'Simone Biles', 'Katie Ledecky', 'Allyson Felix', 'Carl Lewis', 'Jesse Owens', 'Jackie Joyner-Kersee', 'Shaquille O\'Neal', 'Magic Johnson', 'Larry Bird', 'Kareem Abdul-Jabbar', 'Wilt Chamberlain', 'Bill Russell', 'Tim Duncan', 'Kevin Durant', 'Stephen Curry', 'James Harden', 'Giannis Antetokounmpo', 'Luka Doncic', 'Babe Ruth', 'Hank Aaron', 'Willie Mays', 'Derek Jeter', 'Alex Rodriguez', 'Mike Trout', 'Shohei Ohtani', 'Jackie Robinson', 'Ken Griffey Jr', 'Barry Bonds', 'Yogi Berra', 'Lou Gehrig', 'Joe DiMaggio', 'Ted Williams', 'Cy Young', 'Sandy Koufax', 'Nolan Ryan', 'Randy Johnson', 'Pedro Martinez', 'Clayton Kershaw', 'Mariano Rivera', 'Bo Jackson', 'Deion Sanders', 'Jim Thorpe', 'Jim Brown', 'Walter Payton', 'Barry Sanders', 'Emmitt Smith', 'Lawrence Taylor', 'Reggie White'],
  tv_shows: ['Friends', 'Seinfeld', 'The Office', 'Parks and Recreation', 'Brooklyn Nine-Nine', 'How I Met Your Mother', 'The Big Bang Theory', 'Modern Family', 'Arrested Development', 'Community', 'Scrubs', 'Cheers', 'Frasier', 'Breaking Bad', 'Better Call Saul', 'The Sopranos', 'The Wire', 'Mad Men', 'Game of Thrones', 'House of the Dragon', 'The Last of Us', 'Stranger Things', 'The Crown', 'Succession', 'Ozark', 'Narcos', 'Peaky Blinders', 'Vikings', 'The Witcher', 'The Mandalorian', 'Andor', 'WandaVision', 'Loki', 'The Walking Dead', 'Fear the Walking Dead', 'Lost', 'Heroes', 'Prison Break', 'Dexter', 'True Blood', 'Westworld', 'True Detective', 'Fargo', 'The Handmaid\'s Tale', 'Black Mirror', 'Sherlock', 'Doctor Who', 'Peaky Blinders', 'Downton Abbey', 'The Boys', 'Invincible', 'The Umbrella Academy', 'Lucifer', 'Supernatural', 'Arrow', 'The Flash', 'Legends of Tomorrow', 'Supergirl', 'Smallville', 'Gotham', 'Batwoman', 'Titans', 'Doom Patrol', 'The Simpsons', 'Family Guy', 'South Park', 'American Dad', 'Bob\'s Burgers', 'Rick and Morty', 'Futurama', 'King of the Hill', 'BoJack Horseman', 'Big Mouth', 'Grey\'s Anatomy', 'ER', 'House', 'The Good Doctor', 'Chicago Med', 'New Amsterdam', 'The Resident', 'Law & Order', 'Law & Order SVU', 'NCIS', 'CSI', 'Criminal Minds', 'Blue Bloods', 'Bones', 'Castle', 'The Blacklist', 'Person of Interest', 'Homeland', 'The Americans', 'Billions', 'Suits', 'White Collar', 'Burn Notice', 'Chuck', '24', 'Alias'],
  world_leaders: ['George Washington', 'Abraham Lincoln', 'Theodore Roosevelt', 'Franklin Roosevelt', 'John F Kennedy', 'Ronald Reagan', 'Barack Obama', 'Donald Trump', 'Joe Biden', 'Winston Churchill', 'Margaret Thatcher', 'Tony Blair', 'Queen Elizabeth II', 'King Charles III', 'Napoleon Bonaparte', 'Julius Caesar', 'Alexander the Great', 'Genghis Khan', 'Cleopatra', 'Catherine the Great', 'Peter the Great', 'Queen Victoria', 'Otto von Bismarck', 'Adolf Hitler', 'Joseph Stalin', 'Vladimir Lenin', 'Vladimir Putin', 'Mikhail Gorbachev', 'Boris Yeltsin', 'Xi Jinping', 'Mao Zedong', 'Deng Xiaoping', 'Kim Jong Un', 'Kim Il Sung', 'Kim Jong Il', 'Fidel Castro', 'Che Guevara', 'Hugo Chavez', 'Benito Mussolini', 'Francisco Franco', 'Salazar', 'Nelson Mandela', 'Desmond Tutu', 'Mahatma Gandhi', 'Jawaharlal Nehru', 'Indira Gandhi', 'Narendra Modi', 'Muhammad Ali Jinnah', 'Benazir Bhutto', 'Imran Khan', 'Aung San Suu Kyi', 'Lee Kuan Yew', 'Sukarno', 'Suharto', 'Ho Chi Minh', 'Pol Pot', 'Saddam Hussein', 'Muammar Gaddafi', 'Hosni Mubarak', 'Anwar Sadat', 'Gamal Abdel Nasser', 'Yasser Arafat', 'Benjamin Netanyahu', 'Golda Meir', 'Yitzhak Rabin', 'David Ben-Gurion', 'Mohammad Reza Pahlavi', 'Ayatollah Khomeini', 'Recep Erdogan', 'Ataturk', 'Angela Merkel', 'Helmut Kohl', 'Willy Brandt', 'Charles de Gaulle', 'Emmanuel Macron', 'Nicolas Sarkozy', 'Jacques Chirac', 'Francois Mitterrand', 'Justin Trudeau', 'Pierre Trudeau', 'Stephen Harper', 'Lula da Silva', 'Jair Bolsonaro', 'Juan Peron', 'Eva Peron', 'Simon Bolivar', 'Augusto Pinochet', 'Salvador Allende', 'Hugo Chavez', 'Benito Juarez', 'Porfirio Diaz', 'Pancho Villa', 'Emiliano Zapata', 'Pope Francis', 'Pope John Paul II', 'Dalai Lama', 'Martin Luther King Jr', 'Malcolm X'],
  household_items: ['Bedroom', 'Living Room', 'Kitchen', 'Bathroom', 'Dining Room', 'Garage', 'Attic', 'Basement', 'Laundry Room', 'Closet', 'Pantry', 'Foyer', 'Hallway', 'Study', 'Den', 'Guest Room', 'Master Bedroom', 'Nursery', 'Playroom', 'Home Office', 'Mudroom', 'Sunroom', 'Porch', 'Patio', 'Deck', 'Balcony', 'Sofa', 'Couch', 'Armchair', 'Recliner', 'Coffee Table', 'End Table', 'TV Stand', 'Entertainment Center', 'Bookshelf', 'Bed', 'Mattress', 'Nightstand', 'Dresser', 'Wardrobe', 'Desk', 'Chair', 'Dining Table', 'Kitchen Table', 'Bar Stool', 'Bench', 'Ottoman', 'Lamp', 'Floor Lamp', 'Table Lamp', 'Chandelier', 'Ceiling Fan', 'Curtains', 'Blinds', 'Drapes', 'Rug', 'Carpet', 'Mirror', 'Picture Frame', 'Clock', 'Vase', 'Plant', 'Pillow', 'Blanket', 'Comforter', 'Sheet', 'Pillowcase', 'Towel', 'Shower Curtain', 'Bath Mat', 'Toilet', 'Sink', 'Bathtub', 'Shower', 'Cabinet', 'Drawer', 'Refrigerator', 'Stove', 'Oven', 'Microwave', 'Dishwasher', 'Blender', 'Toaster', 'Coffee Maker', 'Kettle', 'Cutting Board', 'Knife', 'Fork', 'Spoon', 'Plate', 'Bowl', 'Cup', 'Mug', 'Glass', 'Pan', 'Pot', 'Vacuum', 'Broom', 'Mop', 'Dustpan', 'Iron', 'Ironing Board'],
  office_items: ['Conference Room', 'Meeting Room', 'Cubicle', 'Office', 'Reception', 'Lobby', 'Break Room', 'Copy Room', 'Mail Room', 'Server Room', 'Storage Room', 'Boardroom', 'Executive Office', 'Open Office', 'Workstation', 'Desk', 'Office Chair', 'Ergonomic Chair', 'Standing Desk', 'Filing Cabinet', 'Bookcase', 'Shelf', 'Drawer', 'Computer', 'Monitor', 'Keyboard', 'Mouse', 'Laptop', 'Desktop', 'Printer', 'Scanner', 'Copier', 'Fax Machine', 'Shredder', 'Telephone', 'Phone', 'Headset', 'Webcam', 'Projector', 'Screen', 'Whiteboard', 'Bulletin Board', 'Cork Board', 'Calendar', 'Planner', 'Notebook', 'Binder', 'Folder', 'File', 'Paper', 'Envelope', 'Stapler', 'Staples', 'Paper Clip', 'Binder Clip', 'Rubber Band', 'Tape', 'Tape Dispenser', 'Scissors', 'Pen', 'Pencil', 'Marker', 'Highlighter', 'Eraser', 'Ruler', 'Calculator', 'Sticky Notes', 'Post-it', 'Notepad', 'Legal Pad', 'Business Card', 'Name Tag', 'Badge', 'Lanyard', 'Coffee Mug', 'Water Cooler', 'Coffee Machine', 'Microwave', 'Refrigerator', 'Vending Machine', 'Coat Rack', 'Umbrella Stand', 'Trash Can', 'Recycling Bin', 'Clock', 'Plant', 'Lamp', 'Desk Lamp', 'Filing System', 'In-Tray', 'Out-Tray', 'Pencil Holder', 'Desk Organizer', 'Mouse Pad', 'Keyboard Tray', 'Monitor Stand', 'Cable Management', 'Extension Cord', 'Power Strip', 'USB Drive', 'External Hard Drive'],
  pirates_ships: ['Pirate', 'Captain', 'First Mate', 'Quartermaster', 'Boatswain', 'Sailor', 'Crew', 'Buccaneer', 'Privateer', 'Corsair', 'Swashbuckler', 'Sea Dog', 'Ship', 'Vessel', 'Boat', 'Galleon', 'Frigate', 'Sloop', 'Brig', 'Schooner', 'Brigantine', 'Caravel', 'Clipper', 'Yacht', 'Sailboat', 'Warship', 'Battleship', 'Cruiser', 'Destroyer', 'Submarine', 'Aircraft Carrier', 'Tugboat', 'Ferry', 'Barge', 'Raft', 'Canoe', 'Kayak', 'Anchor', 'Mast', 'Sail', 'Rigging', 'Hull', 'Deck', 'Bow', 'Stern', 'Port', 'Starboard', 'Helm', 'Rudder', 'Keel', 'Cannon', 'Cutlass', 'Sword', 'Pistol', 'Musket', 'Dagger', 'Hook', 'Peg Leg', 'Eye Patch', 'Parrot', 'Treasure', 'Gold', 'Doubloon', 'Pieces of Eight', 'Chest', 'Map', 'Compass', 'Spyglass', 'Telescope', 'Flag', 'Jolly Roger', 'Skull and Crossbones', 'Crow\'s Nest', 'Plank', 'Mutiny', 'Scurvy', 'Grog', 'Rum', 'Shanty', 'Aye Aye', 'Ahoy', 'Avast', 'Yo Ho Ho', 'Shiver Me Timbers', 'Landlubber', 'Scallywag', 'Barnacle', 'Kraken', 'Mermaid', 'Siren', 'Davy Jones', 'Davy Jones Locker', 'Marooned', 'Castaway', 'Deserted Island', 'Port', 'Harbor', 'Dock', 'Wharf', 'Pier', 'Lighthouse', 'Voyage', 'Journey', 'Expedition'],
  nature: ['Ocean', 'Sea', 'Wave', 'Tide', 'Current', 'Surf', 'Beach', 'Shore', 'Coast', 'Shoreline', 'Coastline', 'Bay', 'Cove', 'Gulf', 'Strait', 'Channel', 'Reef', 'Coral', 'Lagoon', 'Atoll', 'Island', 'Peninsula', 'Cape', 'River', 'Stream', 'Creek', 'Brook', 'Tributary', 'Rapids', 'Waterfall', 'Cascade', 'Lake', 'Pond', 'Pool', 'Spring', 'Geyser', 'Hot Spring', 'Mountain', 'Peak', 'Summit', 'Ridge', 'Hill', 'Valley', 'Canyon', 'Gorge', 'Ravine', 'Cliff', 'Bluff', 'Plateau', 'Mesa', 'Butte', 'Forest', 'Woods', 'Jungle', 'Rainforest', 'Tree', 'Oak', 'Pine', 'Maple', 'Birch', 'Willow', 'Palm', 'Redwood', 'Sequoia', 'Desert', 'Dune', 'Oasis', 'Cactus', 'Sand', 'Rock', 'Stone', 'Boulder', 'Pebble', 'Gravel', 'Meadow', 'Field', 'Prairie', 'Plain', 'Grassland', 'Savanna', 'Tundra', 'Steppe', 'Swamp', 'Marsh', 'Bog', 'Wetland', 'Mangrove', 'Cave', 'Cavern', 'Grotto', 'Volcano', 'Lava', 'Magma', 'Crater', 'Glacier', 'Iceberg', 'Ice Cap', 'Snowfield', 'Avalanche', 'Sky', 'Cloud', 'Rain', 'Snow', 'Hail', 'Sleet'],
  military_government: ['Army', 'Navy', 'Air Force', 'Marines', 'Coast Guard', 'Military', 'Soldier', 'Sailor', 'Airman', 'Marine', 'Veteran', 'General', 'Admiral', 'Colonel', 'Major', 'Captain', 'Lieutenant', 'Sergeant', 'Corporal', 'Private', 'Commander', 'Officer', 'Enlisted', 'Recruit', 'Cadet', 'Battalion', 'Brigade', 'Division', 'Regiment', 'Squadron', 'Platoon', 'Company', 'Unit', 'Troop', 'Tank', 'Jeep', 'Humvee', 'APC', 'Fighter Jet', 'Bomber', 'Helicopter', 'Drone', 'Missile', 'Rocket', 'Grenade', 'Rifle', 'Gun', 'Pistol', 'Machine Gun', 'Bayonet', 'Ammunition', 'Bomb', 'Mine', 'Torpedo', 'Artillery', 'Mortar', 'Cannon', 'Bunker', 'Trench', 'Foxhole', 'Barracks', 'Base', 'Fort', 'Camp', 'Pentagon', 'War', 'Battle', 'Combat', 'Operation', 'Mission', 'Campaign', 'Strategy', 'Tactics', 'Defense', 'Offense', 'Attack', 'Retreat', 'Surrender', 'Victory', 'Defeat', 'Government', 'Congress', 'Senate', 'House', 'Parliament', 'Legislature', 'Executive', 'Judicial', 'Legislative', 'President', 'Vice President', 'Senator', 'Representative', 'Congressman', 'Governor', 'Mayor', 'Ambassador', 'Diplomat', 'Cabinet', 'Secretary', 'Minister', 'Prime Minister', 'Chancellor', 'Constitution', 'Law', 'Bill', 'Act', 'Amendment', 'Veto', 'Vote', 'Election', 'Democracy', 'Republic', 'Monarchy', 'Dictatorship', 'Regime', 'Treaty', 'Alliance', 'NATO', 'UN', 'United Nations', 'Security Council', 'CIA', 'FBI', 'NSA', 'Homeland Security', 'Secret Service', 'Intelligence', 'Espionage', 'Spy', 'Agent', 'Classified', 'Top Secret'],
  desserts: ['Pie', 'Tart', 'Cheesecake', 'Tiramisu', 'Brownie', 'Cookie', 'Biscuit', 'Scone', 'Muffin', 'Cupcake', 'Donut', 'Croissant', 'Danish', 'Eclair', 'Macaron', 'Cannoli', 'Baklava', 'Strudel', 'Crepe', 'Pancake', 'Waffle', 'French Toast', 'Pudding', 'Custard', 'Mousse', 'Parfait', 'Trifle', 'Souffle', 'Creme Brulee', 'Panna Cotta', 'Flan', 'Gelato', 'Sorbet', 'Sherbet', 'Frozen Yogurt', 'Milkshake', 'Smoothie', 'Float', 'Sundae', 'Banana Split', 'Apple Pie', 'Cherry Pie', 'Pumpkin Pie', 'Pecan Pie', 'Key Lime Pie', 'Lemon Meringue', 'Fruit Tart', 'Chocolate Cake', 'Vanilla Cake', 'Red Velvet', 'Carrot Cake', 'Black Forest', 'Pound Cake', 'Angel Food Cake', 'Marble Cake', 'Coffee Cake', 'Bundt Cake', 'Layer Cake', 'Sheet Cake', 'Birthday Cake', 'Wedding Cake', 'Cobbler', 'Crisp', 'Crumble', 'Buckle', 'Betty', 'Turnover', 'Fritter', 'Beignet', 'Funnel Cake', 'Churro', 'Sopapilla', 'Zeppole', 'Profiterole', 'Cream Puff', 'Boston Cream', 'Jelly Roll', 'Swiss Roll', 'Cinnamon Roll', 'Sticky Bun', 'Bear Claw', 'Apple Turnover', 'Fruit Cobbler', 'Bread Pudding', 'Rice Pudding', 'Chocolate Chip Cookie', 'Oatmeal Cookie', 'Sugar Cookie', 'Snickerdoodle', 'Gingerbread', 'Shortbread', 'Biscotti', 'Macaroon', 'Meringue', 'Pavlova', 'Eton Mess', 'Banoffee Pie'],
  mythology: ['Zeus', 'Hera', 'Poseidon', 'Hades', 'Athena', 'Apollo', 'Artemis', 'Ares', 'Aphrodite', 'Hephaestus', 'Hermes', 'Dionysus', 'Demeter', 'Hestia', 'Persephone', 'Hercules', 'Achilles', 'Odysseus', 'Perseus', 'Theseus', 'Jason', 'Orpheus', 'Prometheus', 'Atlas', 'Titan', 'Olympian', 'Thor', 'Odin', 'Loki', 'Freya', 'Baldur', 'Heimdall', 'Tyr', 'Frigg', 'Valkyrie', 'Asgard', 'Valhalla', 'Ragnarok', 'Mjolnir', 'Yggdrasil', 'Ra', 'Osiris', 'Isis', 'Horus', 'Anubis', 'Set', 'Thoth', 'Bastet', 'Sekhmet', 'Ptah', 'Amun', 'Sobek', 'Pharaoh', 'Sphinx', 'Pyramid', 'Mummy', 'Scarab', 'Ankh', 'Shiva', 'Vishnu', 'Brahma', 'Ganesha', 'Hanuman', 'Krishna', 'Rama', 'Kali', 'Lakshmi', 'Saraswati', 'Indra', 'Garuda', 'Amaterasu', 'Susanoo', 'Tsukuyomi', 'Izanagi', 'Izanami', 'Inari', 'Raijin', 'Fujin', 'Quetzalcoatl', 'Tezcatlipoca', 'Huitzilopochtli', 'Tlaloc', 'Xiuhtecuhtli', 'Xolotl', 'Anansi', 'Coyote', 'Raven', 'Thunderbird', 'Wendigo', 'Skinwalker', 'Baba Yaga', 'Medusa', 'Minotaur', 'Centaur', 'Satyr', 'Nymph', 'Siren', 'Harpy', 'Gorgon', 'Cyclops']
};

// Similar categories for medium difficulty
const similarCategories = {
  sports: ['professions', 'famous_athletes'],
  animals: ['food', 'fictional_creatures'],
  countries: ['places', 'world_leaders'],
  places: ['countries', 'household_items', 'office_items'],
  books: ['school', 'movies', 'tv_shows'],
  school: ['books', 'professions', 'office_items'],
  professions: ['sports', 'school', 'world_leaders', 'military_government'],
  movies: ['books', 'tv_shows'],
  food: ['animals', 'candy', 'desserts'],
  candy: ['food', 'desserts'],
  fictional_creatures: ['animals', 'mythology'],
  famous_athletes: ['sports', 'professions'],
  tv_shows: ['movies', 'books'],
  world_leaders: ['professions', 'countries', 'military_government'],
  household_items: ['places', 'office_items'],
  office_items: ['household_items', 'school', 'places'],
  pirates_ships: ['nature', 'professions', 'military_government'],
  nature: ['places', 'pirates_ships'],
  military_government: ['world_leaders', 'professions', 'pirates_ships'],
  desserts: ['candy', 'food'],
  mythology: ['fictional_creatures', 'books']
};

// Get a random word from a category
function getRandomWord(category) {
  const words = wordBank[category];
  return words[Math.floor(Math.random() * words.length)];
}

// Get two words for easy difficulty (same category)
function getEasyWords() {
  const categories = Object.keys(wordBank);
  const category = categories[Math.floor(Math.random() * categories.length)];
  
  const words = wordBank[category];
  const word1Index = Math.floor(Math.random() * words.length);
  let word2Index = Math.floor(Math.random() * words.length);
  
  // Ensure different words
  while (word2Index === word1Index) {
    word2Index = Math.floor(Math.random() * words.length);
  }
  
  return {
    normalWord: words[word1Index],
    imposterWord: words[word2Index],
    category: category,
    difficulty: 'easy'
  };
}

// Get two words for medium difficulty (similar categories)
function getMediumWords() {
  const categories = Object.keys(wordBank);
  const category1 = categories[Math.floor(Math.random() * categories.length)];
  
  // Get similar category
  const similarCats = similarCategories[category1] || [];
  const category2 = similarCats.length > 0 
    ? similarCats[Math.floor(Math.random() * similarCats.length)]
    : category1;
  
  return {
    normalWord: getRandomWord(category1),
    imposterWord: getRandomWord(category2),
    category: `${category1} vs ${category2}`,
    difficulty: 'medium'
  };
}

// Get two words for hard difficulty (completely different categories)
function getHardWords() {
  const categories = Object.keys(wordBank);
  const category1Index = Math.floor(Math.random() * categories.length);
  let category2Index = Math.floor(Math.random() * categories.length);
  
  // Ensure different categories
  while (category2Index === category1Index) {
    category2Index = Math.floor(Math.random() * categories.length);
  }
  
  return {
    normalWord: getRandomWord(categories[category1Index]),
    imposterWord: getRandomWord(categories[category2Index]),
    category: `${categories[category1Index]} vs ${categories[category2Index]}`,
    difficulty: 'hard'
  };
}

// Get words based on difficulty
function getWords(difficulty = 'easy') {
  switch (difficulty) {
    case 'easy':
      return getEasyWords();
    case 'medium':
      return getMediumWords();
    case 'hard':
      return getHardWords();
    default:
      return getEasyWords();
  }
}

module.exports = {
  wordBank,
  getWords,
  getEasyWords,
  getMediumWords,
  getHardWords
};
